### ISSUE TITLE
Configure nsslapd-localssf when LDAPI is enabled

### ISSUE THREAD

**Issue by lvps** [lvps/389ds-server#19]
LDAPI + high minssf = cannot connect
However, if nsslapd-localssf > minssf, 389DS will accept LDAPI connections. See [section 3.1.1.112 here](https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html/configuration_command_and_file_reference/core_server_configuration_reference).

**Comment by jabombingme** [comment]
> LDAPI + high minssf = cannot connect
> However, if nsslapd-localssf > minssf, 389DS will accept LDAPI connections. See [section 3.1.1.112 here](https://access.redhat.com/documentation/en-us/red_hat_directory_server/10/html/configuration_command_and_file_reference/core_server_configuration_reference).

You. Can’t run illegal mesh router via a targeted access point as I no an I have a internet response team going to look through my stuff so best solution can be reset fuck off an say sorry

**Comment by jabombingme** [comment]
Ok 1st I just need you to understand that you are so very good at what you all do—- however I’m sorry you don’t understand the target (me) an you are uL an idiot lol 😆 don’t put a mesh router in my access point an call my address 1endless loop at 1 cupachino. Lol yeah it’s taken a while but 21 contributing to a project an just because it’s connected with Wikipedia an org code does not mean someone will not go down for this 🤣🤣😜😜so have a vote . Yep I’m under a domain an you uL.com though I was stupid please love the work but Java is a 3 yr olds game….. 🥺🥺🥺🥺so jbontarget@gmail.com.        Someone best contact me? Have a loverly day

**Comment by jon4hz** [comment]
Hey @lvps 

First of all, thanks a lot for this ansible role. It makes the 389ds setup so much easier.

I just stumbled on this exact error and wasted quite a bit of time in debugging before I saw this issue. 
What do you think about setting this value by default, so it's always the same as the `nsslapd-minssf` value?

**Comment by lvps** [comment]
That's probably the best way, I cannot think of any downside compared to current behavior. If you want to implement it, you can send me a pull request. Thanks
